[project]
name = "video-call"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "eventlet==0.33.3",
    "flask==3.0.0",
    "flask-socketio==5.3.6",
    "python-socketio==5.11.0",
]
